name: zenit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flash: ^3.1.1
  fl_chart: ^0.69.0
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_markdown: ^0.7.3
  google_fonts: ^6.3.2
  google_nav_bar: ^5.0.7
  intl: ^0.20.2
  image_picker: ^1.1.2
  http: ^1.2.2
  material_symbols_icons: ^4.2928.1
  liquid_progress_indicator_v2: ^0.5.0
  provider: ^6.1.5+1
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  # Di chuyển 2 thằng này vào đúng hàng của dev_dependencies
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/opening_screen_white_bg.png
    - assets/images/ai_loader.gif
    - assets/icons/

  fonts:
    - family: GoogleSansFlex 
      fonts:
        - asset: assets/fonts/GoogleSansFlex.ttf
    - family: MaterialSymbolsRounded
      fonts:
        - asset: assets/icons/MaterialSymbolsRounded.ttf