sonar.projectKey=DACN-DATN-magift-shun_Zenit-app
sonar.organization=dacn-datn-magift-shun
# Chỉ quét code trong lib để tính coverage
sonar.sources=lib

# Chỉ coi folder test là nơi chứa Unit Test
sonar.tests=test

# Quan trọng: Loại bỏ folder integration_test khỏi phạm vi quét code chính
# để nó không báo lỗi "thiếu test" cho mấy cái file flow của mày
sonar.exclusions=integration_test/**, lib/**/*.g.dart, lib/**/*.freezed.dart
sonar.branch.name=manage-feat